### ISSUE TITLE
Data Insertion Failed Error

### ISSUE THREAD

**Issue by Manan-31** [moh53n/FitBridge#4]
When running the script after setting it up, it give the following output:

`Steps: Read 689 Rows
The dataset insertion failed: 400 Bad Request {
  "error": {
    "code": 400,
    "message": "DataPoint out of range: com.google.step_count.delta [2024-02-10T05:09:00Z - 2024-02-10T05:09:10Z] [114] derived:com.google.step_count.delta:1013459681698:FitBridge:FitBridge:1:FitBridgge",
    "errors": [
      {
        "message": "DataPoint out of range: com.google.step_count.delta [2024-02-10T05:09:00Z - 2024-02-10T05:09:10Z] [114] derived:com.google.step_count.delta:1013459681698:FitBridge:FitBridge:1:FitBridgge",
        "domain": "global",
        "reason": "invalidArgument"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}

Steps: The latest timestamp inserted is 1707857050
Heart Rate: Read 0 Rows`

**Comment by moh53n** [comment]
There was a bug in the steps data point where endTimeNanos was incorrectly set (as a quick fix) and caused trouble with intense activities. I don't have a MI Band anymore but it must be fixed.
    
Update FitBridge using this command:
`pip install FitBridge --upgrade`
And try again. Please let me know if it's fixed. @Manan-31

**Comment by Manan-31** [comment]
> There was a bug in the steps data point where endTimeNanos was incorrectly set (as a quick fix) and caused trouble with intense activities. I don't have a MI Band anymore but it must be fixed.
> 
> Update FitBridge using this command: `pip install FitBridge --upgrade` And try again. Please let me know if it's fixed. @Manan-31

The issue has been fixed. 
Thank you so much for the update.
