### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by anbuchelva** [moh53n/FitBridge#6]
hi @moh53n,

Its not an *issue* and I would like to **thank you** 🙏  for creating this project.  
As you mentioned it is not that complex to implement, the documentation is clear and it is easy to setup.  

This is my setup, which may help someone who likes to follow the same.
1. Gadget bridge takes auto backup the db in a separate folder where it can be accessible by user.
2. Syncthing sync it when there is a change in the db to a local home server.
3. A cron job that runs FitBridge command for every hour to push the data to google fit.

You may close it!

Edit: You may convert the epoch time to human readable date & time format when the sync is completed.

**Comment by moh53n** [comment]
Hi @anbuchelva,
Thank you for your kind words! I really appreciate it.
I changed the mentioned timestamp message per your suggestion.

**Comment by anbuchelva** [comment]
It works as expected.

![image](https://github.com/moh53n/FitBridge/assets/5076760/db247f0c-c88b-4d56-9e46-d32a1d349ebf)
